[package]
name = "shared"
version = "0.1.2"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]


[dependencies]
serde = { version = "1", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sqlx = "0.8.0"
