name: Build Android APK

on:
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get build tool versions
        id: build_tool_versions
        shell: bash
        run: sed "s/ /=/" .build-tool-versions >> "$GITHUB_OUTPUT"

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.build_tool_versions.outputs.rust }}
          targets: wasm32-unknown-unknown,aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: Cache the rust details
        uses: Swatinem/rust-cache@v2
        with:
          cache-targets: true
          cache-workspace-crates: true
          cache-bin: true

      - name: Install dependencies
        run: |
          cargo install wasm-bindgen-cli@0.2.106 wasm-opt@0.116.1 tauri-cli@2.9.5 trunk@0.21.14

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ steps.build_tool_versions.outputs.jdk }}
          distribution: 'temurin'
          cache: gradle

      - name: Setup Android SDK
        uses: amyu/setup-android@v5
        with:
          sdk-version: ${{ steps.build_tool_versions.outputs.sdk }}
          ndk-version: ${{ steps.build_tool_versions.outputs.ndk }}

      - name: Setup Android signing
        run: |
          cd crates/tauri/gen/android
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" > keystore.properties
          echo "password=${{ secrets.ANDROID_KEY_PASSWORD }}" >> keystore.properties
          base64 -d <<< "${{ secrets.ANDROID_KEY_BASE64 }}" > $RUNNER_TEMP/keystore.jks
          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> keystore.properties

      - name: Build Tauri Android
        run: |
          export NDK_HOME=$ANDROID_NDK
          cargo tauri android build  --split-per-abi
          mkdir dist
          find  crates/tauri/gen/android/app/build/outputs/apk/ -iname *-release.apk -exec cp {} dist \;
          find  crates/tauri/gen/android/app/build/outputs/bundle/ -iname *-release.aab -exec cp {} dist \;

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*
            LICENSE.md
            PRIVACY_POLICY.md
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
